server.port=8080
spring.application.name=lendbridge-backend
spring.datasource.url=jdbc:postgresql://ep-gentle-mud-ad66q5av-pooler.c-2.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_Xmt9QWS4GOwB
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false
jwt.secret=LendBridge2025SecureKeyForJWTSigning
jwt.expiration-ms=86400000
twilio.account-sid=${TWILIO_ACCOUNT_SID}
twilio.auth-token=${TWILIO_AUTH_TOKEN}
twilio.phone-number=${TWILIO_PHONE_NUMBER}
twilio.enabled=${TWILIO_ENABLED:false}
otp.expiry-minutes=10
otp.length=6
spring.task.scheduling.pool.size=5
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
springdoc.swagger-ui.server-url=https://lendbridge-backend.onrender.com
server.forward-headers-strategy=framework
spring.mvc.cors.allowed-origins=https://lendbridge-frontend.vercel.app